### ISSUE TITLE
Variable definition

### ISSUE THREAD

**Issue by maheshmadpathi** [jtyr/ansible-filebeat#1]
Hi,

Where did you define below variables?

```bash
elastic_yum_repo_url 
elastic_yum_repo_key 
elastic_yum_repo_params
```
Thanks,
Mahesh

**Comment by jtyr** [comment]
Those variables are not defined in the role. You can define them in your `group_vars`. They are meant to help to override the default repo variables for all my Elastic roles ([logstash](https://github.com/jtyr/ansible-logstash), [filebeats](https://github.com/jtyr/ansible-filebeats), [elasticsearch](https://github.com/jtyr/ansible-elasticsearch) and [kibana](https://github.com/jtyr/ansible-kibana)) at once.
