### ISSUE TITLE
no attribute 'os_family'

### ISSUE THREAD

**Issue by Marty** [jtyr/ansible-filebeat#2]
`FAILED! => {"msg": "The conditional check 'ansible_facts.os_family == \"RedHat\" or ansible_facts.os_family == \"Debian\"\n' failed. The error was: error while evaluating conditional (ansible_facts.os_family == \"RedHat\" or ansible_facts.os_family == \"Debian\"\n): 'dict object' has no attribute 'os_family'"}`

In the output of `ansible -m setup` I get `"ansible_os_family": "RedHat"`.
I tried to rename `ansible_facts.os_family` in the `tasks/main.yml` to `ansible_facts.ansible_os_family` and `ansible_os_family` but that didn't work.

```
ansible --version
ansible 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/mas/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

On the target host:

```
 cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
```

I'm new to ansible, do you have any idea what could be wrong?
This does not seem to be too common on the search engines either ...

**Comment by jtyr** [comment]
Please try it with this Playbook:

```yaml
---

- hosts: all
  gather_facts: yes
  connection: local
  tasks:
    - debug:
        msg: "{{ ansible_facts.os_family }}"
```

It gives me this:

```
$ ansible-playbook -i localhost, ./site.yaml

PLAY [all] ***********************************************************************************

TASK [Gathering Facts] ***********************************************************************
ok: [localhost]

TASK [debug] *********************************************************************************
ok: [localhost] => {
    "msg": "RedHat"
}

PLAY RECAP ***********************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by Marty** [comment]
`gather_facts: yes` did the trick, thank you!
